name: rill-platform
services:
  rill-admin:
    image: rill
    working_dir: /app
    command: ["start", "--accept"]
    ports:
      - "8080:8080"  # HTTP port
      - "9090:9090"  # gRPC port
    env_file:
      - .env
    environment:
      - RILL_HOME=/app/data
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=rilluser
      - POSTGRES_PASSWORD=rillpassword
      - POSTGRES_DB=rill
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rilluser -d rill"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rill-cli:
    image: rill
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - RILL_HOME=/app/data
    depends_on:
      - rill-admin

volumes:
  postgres_data:
  redis_data:
